from __future__ import annotations

import io
import os
import re
import subprocess
import zipfile
from collections import deque
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from sqlalchemy.orm import Session

from .models import ClaudeRun
from .run_directory import EXPECTED_OUTPUTS


CLAUDE_BINARY_ENV = "JOBAPPLY_CLAUDE_BINARY"
CLAUDE_DRY_RUN_ENV = "JOBAPPLY_CLAUDE_DRY_RUN"
CLAUDE_EXTRA_ARGS_ENV = "JOBAPPLY_CLAUDE_EXTRA_ARGS"

RUN_LOG_FILENAME = "run.log"
PROMPT_RELPATH = Path("input") / "tailoring_prompt.md"
OUTPUT_DIRNAME = "output"

# Default cap on lines returned by ``read_recent_log_lines`` and on bytes read
# from the log file. Keeps the response small for the polling UI and bounds
# memory use if a runaway Claude run produces a giant log.
DEFAULT_LOG_TAIL_LINES = 40
LOG_READ_MAX_BYTES = 256 * 1024

# Strip the common subset of ANSI escape codes (CSI/SGR) that Claude's stdout
# may carry. We intentionally do not parse OSC sequences — the simple regex
# below is enough to keep recent-activity lines readable in the UI.
_ANSI_ESCAPE_RE = re.compile(r"\x1B\[[0-?]*[ -/]*[@-~]")


def read_recent_log_lines(
    log_path: Path,
    *,
    max_lines: int = DEFAULT_LOG_TAIL_LINES,
    max_bytes: int = LOG_READ_MAX_BYTES,
) -> tuple[list[str], bool]:
    """Return the last ``max_lines`` non-empty lines from ``log_path``.

    Returns ``([], False)`` when the file does not exist. ``truncated`` is
    ``True`` when the file is larger than ``max_bytes`` (we only read the
    tail) or when more than ``max_lines`` non-empty lines exist.
    """
    if not log_path.is_file():
        return [], False
    size = log_path.stat().st_size
    truncated = size > max_bytes
    with log_path.open("rb") as f:
        if truncated:
            f.seek(size - max_bytes)
            # Drop a likely-partial first line after seeking mid-file.
            f.readline()
        raw = f.read()
    text = raw.decode("utf-8", errors="replace")
    tail: deque[str] = deque(maxlen=max_lines)
    total_nonempty = 0
    for line in text.splitlines():
        cleaned = _ANSI_ESCAPE_RE.sub("", line).rstrip()
        if not cleaned:
            continue
        total_nonempty += 1
        tail.append(cleaned)
    if total_nonempty > max_lines:
        truncated = True
    return list(tail), truncated


class ClaudeWorkerError(RuntimeError):
    """Raised when the worker cannot even attempt to invoke Claude Code.

    Process-level failures (non-zero exit, missing binary) are recorded on
    the ``ClaudeRun`` row instead of raising.
    """


def default_claude_binary() -> str:
    return os.environ.get(CLAUDE_BINARY_ENV, "claude")


def is_dry_run() -> bool:
    return os.environ.get(CLAUDE_DRY_RUN_ENV, "").lower() in {"1", "true", "yes", "on"}


def _extra_args() -> list[str]:
    raw = os.environ.get(CLAUDE_EXTRA_ARGS_ENV, "").strip()
    return raw.split() if raw else []


def _now() -> datetime:
    return datetime.now(timezone.utc)


def _record_failure(db: Session, run: ClaudeRun, message: str) -> ClaudeRun:
    run.status = "failed"
    run.error_message = message
    run.completed_at = _now()
    db.commit()
    db.refresh(run)
    return run


def _missing_outputs(run_dir: Path) -> list[str]:
    """Return relative paths of required output files that are absent."""
    output_dir = run_dir / OUTPUT_DIRNAME
    missing: list[str] = []
    for filename in EXPECTED_OUTPUTS:
        if not (output_dir / filename).is_file():
            missing.append(f"{OUTPUT_DIRNAME}/{filename}")
    return missing


def _write_dry_run_outputs(run_dir: Path) -> None:
    """Populate ``output/`` with placeholder files so a dry-run is importable.

    Markdown placeholders are plain text; the DOCX is a minimal valid Word
    package so the open-file flow can hand it to the host application without
    a corrupt-file error.
    """
    output_dir = run_dir / OUTPUT_DIRNAME
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "tailored_resume.md").write_text(
        "# Dry-run tailored resume\n\n(placeholder generated by dry-run worker)\n",
        encoding="utf-8",
    )
    (output_dir / "change_log.md").write_text(
        "# Change log\n\n(placeholder generated by dry-run worker)\n",
        encoding="utf-8",
    )
    (output_dir / "claim_audit.md").write_text(
        "# Claim audit\n\n(placeholder generated by dry-run worker)\n",
        encoding="utf-8",
    )
    _write_minimal_docx(output_dir / "tailored_resume.docx")


def _write_minimal_docx(path: Path) -> None:
    """Write a minimal Word-openable .docx (a zip with the three required parts)."""
    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml"'
        ' ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        '</Types>'
    )
    rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1"'
        ' Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument"'
        ' Target="word/document.xml"/>'
        '</Relationships>'
    )
    document = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        '<w:body><w:p><w:r><w:t>Dry-run placeholder tailored resume.</w:t></w:r></w:p></w:body>'
        '</w:document>'
    )
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("[Content_Types].xml", content_types)
        zf.writestr("_rels/.rels", rels)
        zf.writestr("word/document.xml", document)
    path.write_bytes(buf.getvalue())


def _append_progress(log_path: Path, message: str) -> None:
    """Append a worker-owned progress line to ``run.log``.

    These ``jobapply:`` lines interleave with the raw Claude subprocess output
    so the frontend can show meaningful progress even when Claude is silent.
    Failures to write are swallowed — progress logging must not affect run
    lifecycle.
    """
    try:
        with log_path.open("a", encoding="utf-8") as log:
            log.write(f"jobapply: {message}\n")
    except OSError:
        pass


def invoke_claude_run(
    run_id: str,
    db: Session,
    *,
    claude_binary: Optional[str] = None,
) -> ClaudeRun:
    """Invoke Claude Code synchronously for a previously created run.

    The backend records lifecycle (status, started_at, completed_at,
    error_message) on the ``ClaudeRun`` row. The subprocess only sees the
    run directory as its working directory and must not touch the DB.
    """
    run = db.get(ClaudeRun, run_id)
    if run is None:
        raise ClaudeWorkerError(f"claude run not found: {run_id}")

    run_dir = Path(run.run_dir)
    if not run_dir.is_dir():
        return _record_failure(
            db,
            run,
            f"run directory does not exist: {run_dir}",
        )

    prompt_file = run_dir / PROMPT_RELPATH
    if not prompt_file.is_file():
        return _record_failure(
            db,
            run,
            f"tailoring prompt not found: {prompt_file}",
        )

    log_path = run_dir / RUN_LOG_FILENAME
    # Truncate any prior log so progress lines start fresh per invocation.
    log_path.write_text("", encoding="utf-8")
    _append_progress(log_path, "preparing tailoring inputs")

    run.status = "running"
    run.started_at = _now()
    run.completed_at = None
    run.error_message = None
    db.commit()

    if is_dry_run():
        _append_progress(log_path, "dry-run mode: skipping Claude subprocess")
        _write_dry_run_outputs(run_dir)
        with log_path.open("a", encoding="utf-8") as log:
            log.write(
                f"[dry-run] skipped Claude subprocess at {_now().isoformat()}\n"
                "[dry-run] wrote placeholder output files\n"
            )
        _append_progress(log_path, "validating output files")
        _append_progress(log_path, "output contract satisfied")
        run.status = "completed"
        run.completed_at = _now()
        db.commit()
        db.refresh(run)
        return run

    binary = claude_binary or default_claude_binary()
    argv = [binary, str(PROMPT_RELPATH), *_extra_args()]

    _append_progress(log_path, "launching Claude Code")
    try:
        with log_path.open("a", encoding="utf-8") as log:
            log.write(
                f"$ {' '.join(argv)}  (cwd={run_dir})\n"
            )
            log.flush()
            _append_progress(log_path, "Claude Code process started")
            # The append handle and the milestone helper both append; flushing
            # before the subprocess starts keeps line ordering stable.
            result = subprocess.run(
                argv,
                cwd=str(run_dir),
                stdin=subprocess.DEVNULL,
                stdout=log,
                stderr=subprocess.STDOUT,
                check=False,
            )
    except FileNotFoundError as exc:
        _append_progress(log_path, f"claude binary not found: {binary}")
        _append_progress(log_path, "marking run failed")
        return _record_failure(
            db,
            run,
            f"claude binary not found: {binary} ({exc})",
        )
    except OSError as exc:
        _append_progress(log_path, f"failed to launch claude binary {binary}")
        _append_progress(log_path, "marking run failed")
        return _record_failure(
            db,
            run,
            f"failed to launch claude binary {binary}: {exc}",
        )

    _append_progress(
        log_path, f"Claude Code process exited with code {result.returncode}"
    )

    if result.returncode != 0:
        _append_progress(log_path, "marking run failed")
        run.status = "failed"
        run.error_message = (
            f"claude exited with code {result.returncode}; see {log_path}"
        )
    else:
        _append_progress(log_path, "validating output files")
        missing = _missing_outputs(run_dir)
        if missing:
            for path in missing:
                _append_progress(log_path, f"missing expected output file: {path}")
            _append_progress(log_path, "marking run failed")
            run.status = "failed"
            run.error_message = "expected output file missing: " + ", ".join(missing)
        else:
            _append_progress(log_path, "output contract satisfied")
            run.status = "completed"
            run.error_message = None
    run.completed_at = _now()
    db.commit()
    db.refresh(run)
    return run
