from __future__ import annotations

import shutil
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Optional

from .run_directory import (
    METADATA_FILENAME,
    TAILORING_METHOD_WORD_HANDOFF,
    set_run_status,
    set_tailoring_method,
)

OUTPUT_DIRNAME = "output"
WORD_RESULT_FILENAME = "word_tailored_resume.docx"
FINAL_RESUME_FILENAME = "final_resume.docx"
CHANGE_LOG_FILENAME = "change_log.md"
CLAIM_AUDIT_FILENAME = "claim_audit.md"
ATS_AUDIT_FILENAME = "ats_audit.md"

WAITING_FOR_WORD_RESULT_STATUS = "waiting_for_word_result"
WORD_RESULT_IMPORTED_STATUS = "word_result_imported"
COMPLETED_STATUS = "completed"

_AUDIT_PLACEHOLDER_BODY = """\
Generated by Claude for Word handoff flow.
No structured audit was imported.
Manual review required.
"""

# Layout inside ``runs/<run_id>/word_handoff/``. The numeric prefixes are
# intentional — the directory is opened by a human, and the prefix makes the
# intended reading order obvious.
WORD_HANDOFF_DIRNAME = "word_handoff"
RESUME_DOCX_FILENAME = "01_resume_for_claude_word.docx"
PROMPT_FILENAME = "02_prompt_for_claude_word.txt"
INSTRUCTIONS_FILENAME = "03_instructions.md"

# Required files for a "prepared" handoff. ``RESUME_DOCX_FILENAME`` is
# intentionally not included — a markdown-only run is still considered
# prepared (the operator opens the markdown text in Word manually).
REQUIRED_HANDOFF_FILES: tuple[str, ...] = (
    PROMPT_FILENAME,
    INSTRUCTIONS_FILENAME,
)

RUN_LOG_FILENAME = "run.log"

WORD_HANDOFF_STATUS = "word_handoff_ready"

# Where the user is asked to save the Claude for Word output. Relative to the
# run directory; surfaced to the operator via 03_instructions.md and the run
# log so the import step (a follow-up task) knows where to look.
EXPECTED_WORD_OUTPUT_RELPATH = "output/word_tailored_resume.docx"
FINAL_RESUME_RELPATH = "output/final_resume.docx"

# State labels reported by ``get_word_handoff_status``. These are independent
# of the metadata-level ``status`` field (which describes the broader run
# workflow) — they describe only the on-disk readiness of the handoff
# package and the imported Word result. See task 112.
HANDOFF_STATE_NOT_PREPARED = "not_prepared"
HANDOFF_STATE_PREPARED = "prepared"
HANDOFF_STATE_MISSING_FILES = "missing_files"
HANDOFF_STATE_IMPORT_READY = "import_ready"
HANDOFF_STATE_IMPORTED = "imported"

# Accepted source resume DOCX names, searched in order inside ``input/``.
# ``master_resume.docx`` matches the project's existing input naming; the
# others cover common alternatives an operator might use locally.
ACCEPTED_RESUME_DOCX_NAMES: tuple[str, ...] = (
    "master_resume.docx",
    "resume.docx",
    "base_resume.docx",
    "original_resume.docx",
)

ACCEPTED_RESUME_MD_NAMES: tuple[str, ...] = (
    "master_resume.md",
    "resume.md",
    "base_resume.md",
    "original_resume.md",
)

ACCEPTED_JOB_DESCRIPTION_NAMES: tuple[str, ...] = (
    "job_description.md",
    "job_description.txt",
    "jd.md",
    "jd.txt",
)


class WordHandoffError(ValueError):
    """Raised when a Word handoff package cannot be assembled."""


@dataclass(frozen=True)
class WordHandoffInfo:
    run_dir: Path
    handoff_dir: Path
    resume_docx_copied: bool
    resume_markdown_included: bool


def _find_first_existing(input_dir: Path, names: tuple[str, ...]) -> Optional[Path]:
    for name in names:
        candidate = input_dir / name
        if candidate.is_file():
            return candidate
    return None


def _append_run_log(run_dir: Path, message: str) -> None:
    """Append a worker-style ``jobapply:`` progress line to ``run.log``.

    Best-effort — handoff creation must not fail because of a log write.
    """
    log_path = run_dir / RUN_LOG_FILENAME
    try:
        with log_path.open("a", encoding="utf-8") as f:
            f.write(f"jobapply: {message}\n")
    except OSError:
        pass


def _render_prompt(
    job_description: str,
    *,
    target_job_title: Optional[str] = None,
    target_company: Optional[str] = None,
    resume_markdown: Optional[str] = None,
    evidence_sources_index: Optional[str] = None,
) -> str:
    header_lines = ["Use this document as the source resume and tailor it for the target job."]
    if target_job_title or target_company:
        bits: list[str] = []
        if target_job_title:
            bits.append(f"Target role: {target_job_title}")
        if target_company:
            bits.append(f"Target company: {target_company}")
        header_lines.append(" — ".join(bits))
    parts = [
        *header_lines,
        "",
        "Preserve the master resume's existing visual style, including "
        "the centered name/contact header, colored headings (colored "
        "section headings), separator lines, fonts, spacing, margins, "
        "bullet indentation, and date alignment:",
        "- Keep the centered name/contact header block centered.",
        "- Keep colored section headings (e.g. blue headers stay blue).",
        "- Keep horizontal separator/divider lines that appear in the "
        "master resume.",
        "- Keep bullet lists as bullet lists; do not flatten them into "
        "plain paragraphs.",
        "- Keep fonts, font sizes, margins, section spacing, headings, "
        "bullets, bullet indentation, date alignment, and page layout.",
        "- Preserve bold/italic emphasis patterns and simple separators.",
        "- Edit inside the resume rather than rebuilding the document from scratch.",
        "- Use tracked changes if available.",
        "",
        "Claim and evidence rules:",
        "- Do not invent employers, dates, degrees, technologies, metrics, "
        "publications, awards, responsibilities, or credentials.",
        "- Only strengthen claims that are supported by the original resume "
        "or the evidence sources listed below.",
        "- If a claim is unsupported, omit it rather than weakening it with "
        "vague language.",
        "- Prefer concise, high-signal bullets.",
        "",
        "ATS keyword guidance:",
        "- Mirror exact keywords from the job description where the resume "
        "evidence supports them (tools, technologies, certifications, role "
        "titles).",
        "- Do not pad the resume with keyword lists that are not anchored "
        "to real experience.",
        "- Keep section headings standard (Summary, Skills, Experience, "
        "Education, Projects, Publications) so an ATS can parse them.",
        "- Avoid tables, text boxes, columns, or images for content that "
        "must be ATS-readable.",
        "",
        "Edit these areas first:",
        "1. Summary",
        "2. Skills",
        "3. Most relevant experience bullets",
        "4. Project bullets if they match the job",
        "",
        "After editing, add or update these sections at the end of the document:",
        "CHANGE LOG",
        "CLAIM AUDIT",
        "",
        "## Target Job Description",
        "",
        job_description.rstrip(),
        "",
    ]
    if evidence_sources_index is not None:
        parts.extend(
            [
                "## Evidence Sources Index",
                "",
                evidence_sources_index.rstrip(),
                "",
            ]
        )
    if resume_markdown is not None:
        parts.extend(
            [
                "## Resume Markdown (fallback context)",
                "",
                resume_markdown.rstrip(),
                "",
            ]
        )
    return "\n".join(parts)


_INSTRUCTIONS_BODY = """\
# Claude for Word Handoff Instructions

1. Open 01_resume_for_claude_word.docx in Microsoft Word.
2. Open Claude for Word.
3. Paste the contents of 02_prompt_for_claude_word.txt.
4. Ask Claude to edit using tracked changes.
5. Save the completed file as ../output/word_tailored_resume.docx.
6. Return to JobApplicator and import the Word result.
"""


# Parsed from the leading "# <title> — <company>" line that
# ``run_directory._format_job_description`` writes into ``job_description.md``.
# Used so the prompt can name the target role explicitly without us having to
# widen ``create_word_handoff_package`` to take a ``Job`` row.
def _extract_title_and_company(job_description: str) -> tuple[Optional[str], Optional[str]]:
    for line in job_description.splitlines():
        line = line.strip()
        if not line.startswith("# "):
            continue
        header = line[2:].strip()
        # The em-dash separator is what ``_format_job_description`` writes,
        # but accept a plain dash as a fallback so manually-edited inputs
        # do not break the heuristic.
        for sep in (" — ", " - "):
            if sep in header:
                title, company = header.split(sep, 1)
                return title.strip() or None, company.strip() or None
        return header or None, None
    return None, None


def create_word_handoff_package(
    run_dir: Path,
    *,
    now: Optional[datetime] = None,
) -> WordHandoffInfo:
    """Assemble the Claude for Word handoff package for an existing run.

    Reads source resume + job description from ``<run_dir>/input/`` (accepted
    names listed above), copies the DOCX into ``word_handoff/`` when present,
    writes the prompt / job description / instructions files, and transitions
    metadata to ``tailoring_method=word_handoff`` and
    ``status=word_handoff_ready``.
    """
    run_dir = Path(run_dir)
    if not run_dir.is_dir():
        raise WordHandoffError(f"run directory does not exist: {run_dir}")

    input_dir = run_dir / "input"
    if not input_dir.is_dir():
        raise WordHandoffError(
            f"run input directory does not exist: {input_dir}"
        )

    if not (run_dir / METADATA_FILENAME).is_file():
        raise WordHandoffError(
            f"metadata.json not found in run directory: {run_dir}"
        )

    jd_src = _find_first_existing(input_dir, ACCEPTED_JOB_DESCRIPTION_NAMES)
    if jd_src is None:
        raise WordHandoffError(
            "no job description found in run input "
            f"(expected one of: {list(ACCEPTED_JOB_DESCRIPTION_NAMES)})"
        )

    docx_src = _find_first_existing(input_dir, ACCEPTED_RESUME_DOCX_NAMES)
    md_src = _find_first_existing(input_dir, ACCEPTED_RESUME_MD_NAMES)
    if docx_src is None and md_src is None:
        raise WordHandoffError(
            "no source resume found in run input "
            f"(expected one of: "
            f"{list(ACCEPTED_RESUME_DOCX_NAMES + ACCEPTED_RESUME_MD_NAMES)})"
        )

    handoff_dir = run_dir / WORD_HANDOFF_DIRNAME
    handoff_dir.mkdir(parents=True, exist_ok=True)

    resume_docx_copied = False
    if docx_src is not None:
        shutil.copyfile(docx_src, handoff_dir / RESUME_DOCX_FILENAME)
        resume_docx_copied = True

    jd_text = jd_src.read_text(encoding="utf-8")
    resume_md_text: Optional[str] = None
    if md_src is not None:
        resume_md_text = md_src.read_text(encoding="utf-8")

    target_title, target_company = _extract_title_and_company(jd_text)

    # The evidence sources index lives next to the staged sources at
    # ``input/evidence_sources_index.md``. It exists for every run
    # (``run_directory._stage_evidence_sources`` writes a "(none)" stub
    # when no sources are staged), so include it whenever it is present.
    evidence_index_path = input_dir / "evidence_sources_index.md"
    evidence_index_text: Optional[str] = None
    if evidence_index_path.is_file():
        evidence_index_text = evidence_index_path.read_text(encoding="utf-8")

    prompt_text = _render_prompt(
        jd_text,
        target_job_title=target_title,
        target_company=target_company,
        resume_markdown=resume_md_text,
        evidence_sources_index=evidence_index_text,
    )
    (handoff_dir / PROMPT_FILENAME).write_text(prompt_text, encoding="utf-8")
    (handoff_dir / INSTRUCTIONS_FILENAME).write_text(
        _INSTRUCTIONS_BODY, encoding="utf-8"
    )

    # Persist the workflow transition atomically-enough: both metadata writes
    # happen here so a caller never sees ``tailoring_method=word_handoff``
    # without ``status=word_handoff_ready``.
    set_tailoring_method(run_dir, TAILORING_METHOD_WORD_HANDOFF, now=now)
    set_run_status(run_dir, WORD_HANDOFF_STATUS, now=now)

    _append_run_log(run_dir, "created Claude for Word handoff package")
    _append_run_log(run_dir, f"handoff_dir={handoff_dir}")
    _append_run_log(
        run_dir, f"expected Word output={EXPECTED_WORD_OUTPUT_RELPATH}"
    )

    return WordHandoffInfo(
        run_dir=run_dir,
        handoff_dir=handoff_dir,
        resume_docx_copied=resume_docx_copied,
        resume_markdown_included=resume_md_text is not None,
    )


@dataclass(frozen=True)
class WordResultImportInfo:
    run_dir: Path
    imported: bool
    word_result_path: Path
    final_resume_path: Path
    change_log_placeholder_created: bool
    claim_audit_placeholder_created: bool
    ats_audit_placeholder_created: bool


def _write_audit_placeholder_if_missing(path: Path) -> bool:
    if path.exists():
        return False
    path.write_text(_AUDIT_PLACEHOLDER_BODY, encoding="utf-8")
    return True


def import_word_result(
    run_dir: Path,
    *,
    now: Optional[datetime] = None,
) -> WordResultImportInfo:
    """Import a Claude for Word DOCX result into the run's output directory.

    If ``output/word_tailored_resume.docx`` exists and is non-empty, it is
    copied to ``output/final_resume.docx`` (the source file is preserved).
    Missing ``change_log.md`` / ``claim_audit.md`` get honest placeholders so
    the completed-run shape is consistent with the auto path. The run status
    advances ``waiting_for_word_result`` -> ``word_result_imported`` ->
    ``completed``.

    When the source file does not yet exist, the run is marked
    ``waiting_for_word_result`` and ``imported`` is ``False``.
    """
    run_dir = Path(run_dir)
    if not run_dir.is_dir():
        raise WordHandoffError(f"run directory does not exist: {run_dir}")

    if not (run_dir / METADATA_FILENAME).is_file():
        raise WordHandoffError(
            f"metadata.json not found in run directory: {run_dir}"
        )

    output_dir = run_dir / OUTPUT_DIRNAME
    word_result_path = output_dir / WORD_RESULT_FILENAME
    final_resume_path = output_dir / FINAL_RESUME_FILENAME

    _append_run_log(run_dir, "checking for Claude for Word result")
    _append_run_log(
        run_dir,
        f"expected Word result={OUTPUT_DIRNAME}/{WORD_RESULT_FILENAME}",
    )

    if not word_result_path.is_file() or word_result_path.stat().st_size == 0:
        set_run_status(run_dir, WAITING_FOR_WORD_RESULT_STATUS, now=now)
        _append_run_log(run_dir, "Word result not found yet")
        return WordResultImportInfo(
            run_dir=run_dir,
            imported=False,
            word_result_path=word_result_path,
            final_resume_path=final_resume_path,
            change_log_placeholder_created=False,
            claim_audit_placeholder_created=False,
            ats_audit_placeholder_created=False,
        )

    output_dir.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(word_result_path, final_resume_path)

    if not final_resume_path.is_file() or final_resume_path.stat().st_size == 0:
        raise WordHandoffError(
            "final_resume.docx is missing or empty after import"
        )

    change_log_created = _write_audit_placeholder_if_missing(
        output_dir / CHANGE_LOG_FILENAME
    )
    claim_audit_created = _write_audit_placeholder_if_missing(
        output_dir / CLAIM_AUDIT_FILENAME
    )
    ats_audit_created = _write_audit_placeholder_if_missing(
        output_dir / ATS_AUDIT_FILENAME
    )

    set_run_status(run_dir, WORD_RESULT_IMPORTED_STATUS, now=now)
    set_run_status(run_dir, COMPLETED_STATUS, now=now)

    _append_run_log(
        run_dir,
        f"imported Word result to {OUTPUT_DIRNAME}/{FINAL_RESUME_FILENAME}",
    )

    return WordResultImportInfo(
        run_dir=run_dir,
        imported=True,
        word_result_path=word_result_path,
        final_resume_path=final_resume_path,
        change_log_placeholder_created=change_log_created,
        claim_audit_placeholder_created=claim_audit_created,
        ats_audit_placeholder_created=ats_audit_created,
    )


# --- handoff status (task 112) ---


@dataclass(frozen=True)
class WordHandoffFileStatus:
    """One file in a handoff package, with its run-relative path and presence."""

    name: str
    path: str
    exists: bool


@dataclass(frozen=True)
class WordHandoffStatusInfo:
    """Filesystem-derived view of the Word handoff package for a run.

    Drives the UI's decision to show "not prepared", "prepared",
    "missing files", or "import ready" without depending on
    metadata.json being in sync with the on-disk files.
    """

    state: str
    handoff_dir_relpath: str
    handoff_dir_exists: bool
    resume_docx: WordHandoffFileStatus
    prompt_txt: WordHandoffFileStatus
    instructions_md: WordHandoffFileStatus
    expected_output_docx: WordHandoffFileStatus
    final_resume_docx: WordHandoffFileStatus
    missing_required_files: tuple[str, ...]
    message: str


def _file_status(
    *, name: str, run_dir: Path, relpath: str
) -> WordHandoffFileStatus:
    exists = (run_dir / relpath).is_file()
    return WordHandoffFileStatus(name=name, path=relpath, exists=exists)


def get_word_handoff_status(run_dir: Path) -> WordHandoffStatusInfo:
    """Return the on-disk state of the Word handoff package.

    Pure filesystem check — does not read metadata.json, so the result
    stays consistent even if the handoff folder is deleted out from
    under a run or its metadata says one thing and the disk says
    another. The UI relies on this so it never claims the package is
    prepared before the files actually exist.
    """
    run_dir = Path(run_dir)
    handoff_dir = run_dir / WORD_HANDOFF_DIRNAME

    resume_docx = _file_status(
        name=RESUME_DOCX_FILENAME,
        run_dir=run_dir,
        relpath=f"{WORD_HANDOFF_DIRNAME}/{RESUME_DOCX_FILENAME}",
    )
    prompt_txt = _file_status(
        name=PROMPT_FILENAME,
        run_dir=run_dir,
        relpath=f"{WORD_HANDOFF_DIRNAME}/{PROMPT_FILENAME}",
    )
    instructions_md = _file_status(
        name=INSTRUCTIONS_FILENAME,
        run_dir=run_dir,
        relpath=f"{WORD_HANDOFF_DIRNAME}/{INSTRUCTIONS_FILENAME}",
    )
    expected_output_docx = _file_status(
        name=WORD_RESULT_FILENAME,
        run_dir=run_dir,
        relpath=EXPECTED_WORD_OUTPUT_RELPATH,
    )
    final_resume_docx = _file_status(
        name=FINAL_RESUME_FILENAME,
        run_dir=run_dir,
        relpath=FINAL_RESUME_RELPATH,
    )

    handoff_dir_exists = handoff_dir.is_dir()
    missing_required: list[str] = []
    if handoff_dir_exists:
        for required in REQUIRED_HANDOFF_FILES:
            if not (handoff_dir / required).is_file():
                missing_required.append(required)

    if final_resume_docx.exists:
        state = HANDOFF_STATE_IMPORTED
        message = "Claude for Word result imported."
    elif expected_output_docx.exists:
        state = HANDOFF_STATE_IMPORT_READY
        message = "Word result detected — ready to import."
    elif not handoff_dir_exists:
        state = HANDOFF_STATE_NOT_PREPARED
        message = "Claude for Word handoff is not prepared yet."
    elif missing_required:
        state = HANDOFF_STATE_MISSING_FILES
        message = (
            "Claude for Word handoff folder exists, but required files are "
            "missing: " + ", ".join(missing_required)
        )
    else:
        state = HANDOFF_STATE_PREPARED
        message = "Claude for Word handoff is ready."

    return WordHandoffStatusInfo(
        state=state,
        handoff_dir_relpath=WORD_HANDOFF_DIRNAME,
        handoff_dir_exists=handoff_dir_exists,
        resume_docx=resume_docx,
        prompt_txt=prompt_txt,
        instructions_md=instructions_md,
        expected_output_docx=expected_output_docx,
        final_resume_docx=final_resume_docx,
        missing_required_files=tuple(missing_required),
        message=message,
    )
